[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Nikhil Wankhade",email = "nikhilw395@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard] (>=0.139.2,<0.140.0)",
    "uvicorn (>=0.51.0,<0.52.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "supabase (>=2.31.0,<3.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)",
    "sqlmodel (>=0.0.39,<0.0.40)",
    "psycopg2 (>=2.9.12,<3.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
